name: 'Deploy'

on:
  workflow_call:
    inputs:
      python_version:
        default: '3.13'
        required: false
        type: string
      deploy_script:
        required: false
        type: string
      aws_region:
        required: false
        default: "ap-southeast-1"
        type: string
      runs-on:
        type: string
        required: false
        default: self-hosted
      timeout-minutes:
        type: number
        required: false
        default: 10
    secrets:
      slack_webhook_url:
        description: "notify slack on github action result"
        required: false
      aws_key_id:
        required: false
      aws_secret:
        required: false
      env_base64:
        required: false
      pipy_registry_auth:
        required: false

jobs:
  deploy:
    name: Pass input and secrets to my-action
    runs-on: "${{ inputs.runs-on }}"
    timeout-minutes: ${{ inputs.timeout-minutes }}
    env:
      env_base64: ${{ secrets.env_base64 }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main
      - name: Setup ENV
        if: ${{ env.env_base64 != '' }}
        run: echo ${{ env.env_base64 }} | base64 -d > .env && source .env
      - name: print github context
        run: |
          echo '${{ toJSON(github) }}'
      - uses: actions/setup-python@main
        id: setup-python
        with:
          python-version-file: "pyproject.toml"
          check-latest: true
        if: runner.environment != 'self-hosted'
      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        if: runner.environment != 'self-hosted'
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo Hello, world!
          echo github ref: ${{ github.ref }}
          echo pipenv-cache hit: ${{ steps.setup-python.outputs.cache-hit }}
      - name: install package
        run: |
            IFS=":" read -r USERNAME PASSWORD <<< "$REGISTRY_AUTH"
            export UV_INDEX_PRIVATE_REGISTRY_USERNAME="$USERNAME"
            export UV_INDEX_PRIVATE_REGISTRY_PASSWORD="$PASSWORD"
            uv venv
            uv pip install .
            uv sync
        env:
          REGISTRY_AUTH: ${{ secrets.pipy_registry_auth }}
      - name: deploy
        run: ${{ inputs.deploy_script }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret }}
          AWS_DEFAULT_REGION: ${{ inputs.aws_region }}
          REGISTRY_AUTH: ${{ secrets.pipy_registry_auth }}
      - name: notify slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.slack_webhook_url }} # required
        if: always()
