name: 'Deploy'

on:
  workflow_call:
    inputs:
      python_version:
        default: '3.11'
        required: false
        type: string
      deploy_script:
        required: false
        type: string
      aws_region:
        required: false
        default: "ap-southeast-1"
        type: string
      runs-on:
        type: string
        required: false
        default: self-hosted
    secrets:
      slack_webhook_url:
        description: "notify slack on github action result"
        required: false
      aws_key_id:
        required: false
      aws_secret:
        required: false
      env_base64:
        required: false
      pipy_registry_auth:
        required: false

env:
  PIPENV_VENV_IN_PROJECT: 1
  PIPENV_CUSTOM_VENV_NAME: .venv2
jobs:
  deploy:
    name: Pass input and secrets to my-action
    runs-on: ["${{ inputs.runs-on }}", macOS]
    timeout-minutes: 10
    env:
      env_base64: ${{ secrets.env_base64 }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main
      - name: Setup ENV
        if: ${{ env.env_base64 != '' }}
        run: echo ${{ env.env_base64 }} | base64 -d > .env
      - name: print github context
        run: |
          echo '${{ toJSON(github) }}'
      - uses: actions/setup-python@main
        id: setup-python
        with:
          cache: "pipenv"
          python-version: ${{ inputs.python_version }}
          check-latest: true
        if: inputs.runs-on != 'self-hosted'
      - name: install pipenv
        run: |
          pip install --upgrade pip setuptools wheel
          curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
        if: inputs.runs-on != 'self-hosted'
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo Hello, world!
          echo github ref: ${{ github.ref }}
          echo pipenv-cache hit: ${{ steps.setup-python.outputs.cache-hit }}
      - name: install package
        run: |
          export PIPENV_VENV_IN_PROJECT=1
          pipenv --clear
          pipenv sync
          pipenv run pip install https://github.com/wangsha/Zappa/archive/main.zip
          pipenv run pip list
        env:
          REGISTRY_AUTH: ${{ secrets.pipy_registry_auth }}
        if: steps.setup-python.outputs.cache-hit != 'true'
      - name: deploy
        run: ${{ inputs.deploy_script }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret }}
          AWS_DEFAULT_REGION: ${{ inputs.aws_region }}
          REGISTRY_AUTH: ${{ secrets.pipy_registry_auth }}
      - name: notify slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.slack_webhook_url }} # required
        if: always()
