name: Python CI Workflow

on:
  workflow_call:
    inputs:
      python_version:
        default: '3.11'
        required: false
        type: string
      test_script:
        required: false
        type: string
      deploy_script:
        required: false
        type: string
      setup_mongo:
        default: false
        required: false
        type: boolean
      setup_redis:
        default: false
        required: false
        type: boolean
      pypi_release:
        default: false
        required: false
        type: boolean
      aws_region:
        required: false
        default: "ap-southeast-1"
        type: string
      pipenv_setup_check:
        required: false
        default: true
        type: boolean
      runs-on:
        type: string
        required: false
        default: self-hosted
    secrets:
      pipy_registry_auth:
        required: false
      slack_webhook_url:
        description: "notify slack on github action result"
        required: false
      aws_key_id:
        required: false
      aws_secret:
        required: false
      env_base64:
        required: false


jobs:
  build-and-test:
    name: Build Test and Deploy
    runs-on: ["${{ inputs.runs-on }}", macOS]
    timeout-minutes: 20
    env:
      env_base64: ${{ secrets.env_base64 }}
    steps:
      - uses: supercharge/redis-github-action@1.4.0
        if: inputs.setup_redis && inputs.runs-on != 'self-hosted'
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        id: setup-python
        with:
          cache: "pipenv"
          python-version: ${{ inputs.python_version }}
          check-latest: true
        if: inputs.runs-on != 'self-hosted'
      - name: install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
        if: inputs.runs-on != 'self-hosted'
      - name: Pull pre-commit config
        run: |
          curl -O https://raw.githubusercontent.com/tryagainconcepts/reusable-github-workflows/main/.pre-commit-config.yaml
          curl -O https://raw.githubusercontent.com/tryagainconcepts/reusable-github-workflows/main/pyproject.toml
        if: github.ref != 'refs/heads/main'
      - uses: wangsha/pre-commit-github-action@main
        with:
          extra_args: --all-files
        if: github.ref != 'refs/heads/main'
      - uses: stefanzweifel/git-auto-commit-action@master
        with:
          commit_message: Automated Changes from pre-commit hooks
          file_pattern: ':!.github/'
        if: github.ref != 'refs/heads/main'
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo Hello, world!
          echo github ref: ${{ github.ref }}
          echo pipenv-cache hit: ${{ steps.setup-python.outputs.cache-hit }}
      - name: install package
        run: pipenv sync --dev
        env:
          REGISTRY_AUTH: ${{ secrets.pipy_registry_auth }}
        if: ${{ steps.setup-python.outputs.cache-hit }} == false
      - uses: supercharge/redis-github-action@1.4.0
        if: inputs.setup_redis && inputs.runs-on != 'self-hosted'
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        if: inputs.setup_mongo && inputs.runs-on != 'self-hosted'
      - name: Setup ENV
        if: ${{ env.env_base64 != '' }}
        run: |
          echo ${{ env.env_base64 }} | base64 -d > .env
      - name: run test
        if: inputs.test_script
        run: ${{ inputs.test_script }}
      - name: deploy
        if: endsWith(github.ref, '/main') && inputs.deploy_script
        run: ${{ inputs.deploy_script }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret }}
          AWS_DEFAULT_REGION: ${{ inputs.aws_region }}
      - name: automerge on PR labelled with automerge
        if: github.ref != 'refs/heads/main'
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "automerge,!work in progress"
      - name: bumpversion
        if: endsWith(github.ref, '/main')
        run: |
          pip install --upgrade bump-my-version
          bump-my-version bump ${DEFAULT_BUMP}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: minor
      - name: Push new version tag
        if: endsWith(github.ref, '/main')
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true
      - name: Release pypi on main branch
        if: endsWith(github.ref, '/main') && inputs.pypi_release
        run: |
          pip install s3pypi wheel
          python setup.py sdist bdist_wheel
          s3pypi dist/* --bucket pipy.detalytics.com --unsafe-s3-website --put-root-index -v
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret }}
          AWS_DEFAULT_REGION: ${{ inputs.aws_region }}
      - name: cleanup
        run: |
          pipenv --rm
      - name: notify slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.slack_webhook_url }} # required
        if: always()
  changelog:
      name: Changelog
      runs-on: ubuntu-latest
      timeout-minutes: 10
      if: endsWith(github.ref, '/main')
      needs: build-and-test
      steps:
        - name: Add Changelog
          if: endsWith(github.ref, '/main')
          uses: saadmk11/changelog-ci@v1.1.2
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}